name: Chromium headless test

on:
  workflow_dispatch:

jobs:
  test-chromium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (anche se non serve)
        uses: actions/checkout@v3

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Fetch HTML headless
        run: |
          chromium-browser --headless --disable-gpu \
            --dump-dom "https://www.italiadomani.gov.it/content/sogei-ng/it/it/catalogo-open-data.html?orderby=%40jcr%3Acontent%2FobservationDateInEvidence&sort=desc" \
            > pagina.html

      - name: Upload HTML
        uses: actions/upload-artifact@v4
        with:
          name: pagina
          path: pagina.html
