name: Chromium headless test

on:
  workflow_dispatch:

jobs:
  test-chromium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (anche se non serve)
        uses: actions/checkout@v3

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Fetch HTML headless
        run: |
          google-chrome-stable --headless --disable-gpu \
            --dump-dom "https://www.italiadomani.gov.it/content/sogei-ng/it/it/catalogo-open-data.html?orderby=%40jcr%3Acontent%2FobservationDateInEvidence&sort=desc" \
            > pagina.html

      - name: Upload HTML
        uses: actions/upload-artifact@v4
        with:
          name: pagina
          path: pagina.html
