name: Chromium headless e commit

on:
  workflow_dispatch:

jobs:
  test-chromium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Installa Google Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Crea cartella test/
        run: mkdir -p test

      - name: Scarica HTML camuffando l'user-agent
        run: |
          google-chrome-stable --headless --disable-gpu \
            --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
            --dump-dom "https://www.italiadomani.gov.it/content/sogei-ng/it/it/catalogo-open-data.html?orderby=%40jcr%3Acontent%2FobservationDateInEvidence&sort=desc" \
            > test/pagina.html

      - name: Mostra le prime 20 righe (debug)
        run: head -n 20 test/pagina.html

      - name: Commit e push nel repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add test/pagina.html
          git commit -m "Snapshot HTML con Chromium headless e user-agent spoofato" || echo "Nessuna modifica da committare"
          git push origin HEAD:main

      - name: Upload HTML come artefatto
        uses: actions/upload-artifact@v4
        with:
          name: pagina
          path: test/pagina.html
