name: Chromium headless and commit

on:
  workflow_dispatch:

jobs:
  test-chromium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Create test directory
        run: mkdir -p test

      - name: Fetch HTML headless
        run: |
          google-chrome-stable --headless --disable-gpu \
            --dump-dom "https://www.italiadomani.gov.it/content/sogei-ng/it/it/catalogo-open-data.html?orderby=%40jcr%3Acontent%2FobservationDateInEvidence&sort=desc" \
            > test/pagina.html

      - name: Commit and push file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add test/pagina.html
          git commit -m "Add HTML snapshot from chromium headless"
          git push origin HEAD:main
